[project]
name = "skeleton-recall"
version = "1.0.0"
requires-python = ">=3.10"
description = "Skeleton Recall Loss for Connectivity Conserving and Resource Efficient Segmentation of Thin Tubular Structures, as an extension for nnU-Net."
readme = "readme.md"
license = { file = "LICENSE" }
authors = [
    { name = "Yannick Kirchhoff", email = "yannick.kirchhoff@dkfz-heidelberg.de" }
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    'deep learning',
    'image segmentation',
    'semantic segmentation',
    'medical image analysis',
    'medical image segmentation',
    'thin tubular structures',
    'skeleton recall',
    'nnU-Net',
    'nnunet'
]
dependencies = [
    "nnunetv2>=2.8",  # 2.8 introduced the nnUNet_extTrainer environment variable
    "torch",
    "numpy",
    "scikit-image>=0.19.3",
    "batchgeneratorsv2",
]

[project.urls]
homepage = "https://github.com/MIC-DKFZ/Skeleton-Recall"
repository = "https://github.com/MIC-DKFZ/Skeleton-Recall"

[project.scripts]
skeleton_recall_trainer_path = "skeleton_recall:print_ext_trainer_path"

[build-system]
requires = ["setuptools>=67.8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["skeleton_recall*"]

[tool.codespell]
skip = '.git,*.pdf,*.svg'
#
# ignore-words-list = ''
